[keyboard]
bindings = [

{ key = "N",      mods = "Control|Shift", command.program = "term"                                                 },
{ key = "Escape", mods = "Command|Shift", command.program = "term"                                                 },

{ key = "Equals", mods = "Control",       action = "ResetFontSize"                                                 },
{ key = "Equals", mods = "Command",       action = "ResetFontSize"                                                 },

{ key = "Space",  mods = "Control|Shift", action = "ToggleViMode",             mode = "~AppCursor|~AppKeypad|~Alt" },
{ key = "H",      mods = "Control",       action = "ToggleViMode",             mode = "~AppCursor|~AppKeypad|~Alt" },
{ key = "L",      mods = "Control|Shift", command.program = "alacritty-clear", mode = "~AppCursor|~AppKeypad|~Alt" },
{ key = "Return", mods = "Control|Shift", command.program = "alacritty-clear", mode = "~AppCursor|~AppKeypad|~Alt" },

{ key = "C",      mods = "Control",       action = "ScrollToBottom",           mode = "Vi"                         },
{ key = "C",      mods = "Control",       action = "ToggleViMode",             mode = "Vi"                         },
{ key = "H",      mods = "Control",       action = "ScrollToBottom",           mode = "Vi"                         },
{ key = "L",      mods = "Control|Shift", action = "ScrollToBottom",           mode = "Vi"                         },
{ key = "L",      mods = "Control|Shift", action = "ToggleViMode",             mode = "Vi"                         },
{ key = "Return", mods = "Control|Shift", action = "ScrollToBottom",           mode = "Vi"                         },
{ key = "Return", mods = "Control|Shift", action = "ToggleViMode",             mode = "Vi"                         },
{ key = "Space",  mods = "Control|Shift", action = "ScrollToBottom",           mode = "Vi"                         },

{ key = "Return",                         action = "ToggleViMode",             mode = "Vi|~Search"                 },
{ key = "Return",                         action = "ScrollToBottom",           mode = "Vi|~Search"                 },
{ key = 8,        mods = "Shift",         action = "First",                    mode = "Vi|~Search"                 },
{ key = 41,                               action = "Last",                     mode = "Vi|~Search"                 },
{ key = 27,       mods = "Shift",         action = "FirstOccupied",            mode = "Vi|~Search"                 },
{ key = 2,        mods = "Shift",         action = "Bracket",                  mode = "Vi|~Search"                 },

{ key = "Return", mods = "Shift",         chars = "\u001B[13;2u",              mode = "Alt"                        },
{ key = "Return", mods = "Control",       chars = "\u001B[13;5u",              mode = "Alt"                        },

	]
