#!/bin/bash

# https://github.com/doegox/todo.txt-cli/blob/f5204a12dda79832d096d051b8851170aa5d5cd9/todo.actions.d/archive

usage() {
  echo "    archive KEYWORD"
  echo "      Moves done items containing KEYWORD from todo.txt to done.txt and removes blank lines."
  echo ""
  echo "    archive ITEM#"
  echo "      Moves done item number ITEM# and removes blank lines."
  echo ""
  exit
}

action=$1
shift

[ "$action" = "usage" ] && usage

KEYWORD=$1
if [[ -z "$KEYWORD" ]]; then
	usage
else
	if [[ "$KEYWORD" =~ ^[0-9]+$ ]]; then
		# we got an ITEM to archive
		[ $TODOTXT_VERBOSE -gt 0 ] && sed "$KEYWORD!d" "$TODO_FILE"
		sed "$KEYWORD!d" "$TODO_FILE" >> "$DONE_FILE"
		sed -i.bak "${KEYWORD}d" "$TODO_FILE"
	else
		# we got a keyword
		[ $TODOTXT_VERBOSE -gt 0 ] && grep "^x .*$KEYWORD" "$TODO_FILE"
		grep "^x .*$KEYWORD" "$TODO_FILE" >> "$DONE_FILE"
		sed -i.bak "/^x .*$KEYWORD/d" "$TODO_FILE"
	fi
fi
[ $TODOTXT_VERBOSE -gt 0 ] && echo "TODO:  $TODO_FILE archived."
#defragment blank lines
sed -i.bak -e '/./!d' "$TODO_FILE"
