#!/usr/bin/env bash

arg="${2}"

function usage {
	echo "    $(basename ${0}) <push|pull>"
	echo "      google drive <-> $TODO_DIR"
	echo ""
	exit
}

[ "${1}" = "usage" ] && usage

if [ "${arg}" != "push" -a "${arg}" != "pull" ]; then
	usage
fi

cd "${TODO_DIR}"

dt="$(date '+%Y%m%d_%H%M')"

for prefix in "archive" "done" "todo"; do
	cp -v "${prefix}.txt" "${prefix}.${dt}.txt.pre-${arg}"
done

drive push -no-prompt *".pre-${arg}"

drive "${arg}"

