#!/usr/bin/env bash

action=$1
shift
mode=$1

function usage {
	echo "  $(basename $0)"
	echo "    pull from google drive to $TODO_DIR"
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"

drive pull

