#!/usr/bin/env bash

action=$1
shift
mode=$1

function usage {
	echo "    $(basename $0) [drive options ...]"
	echo "      pull from google drive to $TODO_DIR"
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"

DT="$(date '+%Y%m%d_%H%M')"
cp "todo.txt" "todo.${DT}.beforepull.txt"
cp "done.txt" "done.${DT}.beforepull.txt"
cp "archive.txt" "archive.${DT}.beforepull.txt"

drive pull "$@"
