#!/usr/bin/env bash

action=$1
shift
mode=$1

function usage {
	echo "    $(basename $0) [drive options ...]"
	echo "      push to google drive from $TODO_DIR"
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"

DT="$(date '+%Y%m%d_%H%M')"
cp "todo.txt" "todo.${DT}.beforepush.txt"
cp "done.txt" "done.${DT}.beforepush.txt"
cp "archive.txt" "archive.${DT}.beforepush.txt"

drive push "$@"
