import os

default_background =   '#' + os.environ['BASE16_default_background']
lighter_background =   '#' + os.environ['BASE16_lighter_background']
selection_background = '#' + os.environ['BASE16_selection_background']
comments =             '#' + os.environ['BASE16_comments']
dark_foreground =      '#' + os.environ['BASE16_dark_foreground']
default_foreground =   '#' + os.environ['BASE16_default_foreground']
light_foreground =     '#' + os.environ['BASE16_light_foreground']
# light_background =     '#' + os.environ['BASE16_light_background']
red =                  '#' + os.environ['BASE16_red']
orange =               '#' + os.environ['BASE16_orange']
yellow =               '#' + os.environ['BASE16_yellow']
bright_yellow =        '#' + os.environ['BASE16_bright_yellow']
green =                '#' + os.environ['BASE16_green']
cyan =                 '#' + os.environ['BASE16_cyan']
blue =                 '#' + os.environ['BASE16_blue']
magenta =              '#' + os.environ['BASE16_magenta']
brown =                '#' + os.environ['BASE16_brown']

# only colour that's a setting
c.hints.border = '1px solid ' + brown

c.colors.completion.fg = default_foreground
c.colors.completion.odd.bg = lighter_background
c.colors.completion.even.bg = lighter_background
c.colors.completion.category.fg = blue
c.colors.completion.category.bg = lighter_background
c.colors.completion.category.border.top = lighter_background
c.colors.completion.category.border.bottom = default_foreground
c.colors.completion.item.selected.fg = light_foreground
c.colors.completion.item.selected.bg = selection_background
c.colors.completion.item.selected.border.top = lighter_background
c.colors.completion.item.selected.border.bottom = lighter_background
c.colors.completion.item.selected.match.fg = orange
c.colors.completion.match.fg = orange
c.colors.completion.scrollbar.fg = default_foreground
c.colors.completion.scrollbar.bg = selection_background
c.colors.contextmenu.menu.bg = lighter_background
c.colors.contextmenu.menu.fg = default_foreground
c.colors.contextmenu.selected.bg = selection_background
c.colors.contextmenu.selected.fg = default_foreground
c.colors.contextmenu.disabled.bg = lighter_background
c.colors.contextmenu.disabled.fg = comments
c.colors.downloads.bar.bg = lighter_background
c.colors.downloads.start.fg = default_foreground
c.colors.downloads.start.bg = selection_background
c.colors.downloads.stop.fg = green
c.colors.downloads.stop.bg = selection_background
c.colors.downloads.error.fg = red
c.colors.hints.fg = default_background
c.colors.hints.bg = bright_yellow
c.colors.hints.match.fg = brown
c.colors.keyhint.fg = default_foreground
c.colors.keyhint.suffix.fg = orange
c.colors.keyhint.bg = lighter_background
c.colors.messages.error.fg = red
c.colors.messages.error.bg = lighter_background
c.colors.messages.error.border = lighter_background
c.colors.messages.warning.fg = magenta
c.colors.messages.warning.bg = lighter_background
c.colors.messages.warning.border = lighter_background
c.colors.messages.info.fg = cyan
c.colors.messages.info.bg = lighter_background
c.colors.messages.info.border = lighter_background
c.colors.prompts.fg = default_foreground
c.colors.prompts.border = default_foreground
c.colors.prompts.bg = selection_background
c.colors.prompts.selected.bg = selection_background
c.colors.prompts.selected.fg = orange
c.colors.statusbar.normal.fg = default_foreground
c.colors.statusbar.normal.bg = lighter_background
c.colors.statusbar.insert.fg = blue
c.colors.statusbar.insert.bg = lighter_background
c.colors.statusbar.passthrough.fg = yellow
c.colors.statusbar.passthrough.bg = lighter_background
c.colors.statusbar.private.fg = red
c.colors.statusbar.private.bg = lighter_background
c.colors.statusbar.command.fg = default_foreground
c.colors.statusbar.command.bg = selection_background
c.colors.statusbar.command.private.fg = default_foreground
c.colors.statusbar.command.private.bg = selection_background
c.colors.statusbar.caret.fg = magenta
c.colors.statusbar.caret.bg = lighter_background
c.colors.statusbar.caret.selection.fg = magenta
c.colors.statusbar.caret.selection.bg = lighter_background
c.colors.statusbar.progress.bg = yellow
c.colors.statusbar.url.fg = default_foreground
c.colors.statusbar.url.error.fg = red
c.colors.statusbar.url.hover.fg = light_foreground
c.colors.statusbar.url.success.http.fg = light_foreground
c.colors.statusbar.url.success.https.fg = light_foreground
c.colors.statusbar.url.warn.fg = magenta
c.colors.tabs.bar.bg = lighter_background
c.colors.tabs.indicator.start = yellow
c.colors.tabs.indicator.stop = comments
c.colors.tabs.indicator.error = red
c.colors.tabs.odd.fg = comments
c.colors.tabs.odd.bg = lighter_background
c.colors.tabs.even.fg = comments
c.colors.tabs.even.bg = lighter_background
c.colors.tabs.pinned.even.bg = default_background
c.colors.tabs.pinned.even.fg = default_foreground
c.colors.tabs.pinned.odd.bg = default_background
c.colors.tabs.pinned.odd.fg = default_foreground
c.colors.tabs.pinned.selected.even.bg = selection_background
c.colors.tabs.pinned.selected.even.fg = default_foreground
c.colors.tabs.pinned.selected.odd.bg = selection_background
c.colors.tabs.pinned.selected.odd.fg = default_foreground
c.colors.tabs.selected.odd.fg = light_foreground
c.colors.tabs.selected.odd.bg = selection_background
c.colors.tabs.selected.even.fg = light_foreground
c.colors.tabs.selected.even.bg = selection_background
