# TODO 
# - private

c.bindings.commands = {
	"normal": {
		"<Escape>": "clear-messages ;; clear-keychain ;; search",

		"<Ctrl-Shift-b>": "bookmark-list --tab",
		"<Ctrl-Shift-h>": "history --tab",
		"<Ctrl-Shift-a>": "tab-select",

		"<Ctrl-d>": "scroll-page 0 0.5",
		"<Ctrl-u>": "scroll-page 0 -0.5",

		"<Ctrl-f>": "cmd-set-text /",

		"<Ctrl-t>": "open --tab",

		"<Ctrl-h>": "tab-move -",
		"<Ctrl-l>": "tab-move +",

		"<Alt-d>": "set colors.webpage.darkmode.enabled true",
		"<Alt-l>": "set colors.webpage.darkmode.enabled false",

		"<Alt-b>": "spawn --userscript --verbose qute-bitwarden.py",
		"<Alt-p>": "spawn --userscript --verbose qute-bitwarden.py --password-only",
		"<Alt-u>": "spawn --userscript --verbose qute-bitwarden.py --username-only",

		";d": "hint links download",
		";h": "hint all hover",
		";i": "hint images",
		";o": "hint links fill :open {hint-url}",
		";to": "hint links fill :open --tab {hint-url}",
		";wo": "hint links fill :open --window {hint-url}",
		";y": "hint links yank",
		";Y": "hint links yank-primary",

		"a": "hint all",
		"A": "hint --rapid all tab-bg",
		"ta": "hint all tab",
		"wa": "hint all window",

		"b": "cmd-set-text --space :quickmark-load",
		"tb": "cmd-set-text --space :quickmark-load --tab",
		"wb": "cmd-set-text --space :quickmark-load --window",

		"m": "cmd-set-text --space :bookmark-load",
		"tm": "cmd-set-text --space :bookmark-load --tab",
		"wm": "cmd-set-text --space :bookmark-load --window",

		"ct": "tab-only",
		"ch": "tab-only --next",
		"cl": "tab-only --prev",
		"cw": "window-only",

		"d": "scroll-page 0 0.5",

		"e": "cmd-set-text :open {url:pretty}",
		"E": "edit-url",
		"te": "cmd-set-text :open --tab {url:pretty}",
		"tE": "edit-url --tab",
		"we": "cmd-set-text :open --window {url:pretty}",
		"wE": "edit-url --window",

		"f": "hint links",
		"F": "hint --rapid links tab-bg",
		"tf": "hint links tab",
		"wf": "hint links window",

		"G": "scroll-to-perc",

		"H": "back",
		"th": "back --tab",
		"wh": "back --tab",

		"L": "forward",
		"tl": "forward --tab",
		"wl": "forward --window",

		"h": "tab-prev",
		"l": "tab-next",

		"j": "scroll down",
		"k": "scroll up",

		"n": "search-next",
		"N": "search-prev",

		"o": "cmd-set-text --space :open",
		"to": "cmd-set-text --space :open --tab",
		"wo": "cmd-set-text --space :open --window",

		"p": "open -- {clipboard}",
		"tp": "open --tab -- {clipboard}",
		"wp": "open --window -- {clipboard}",

		"P": "open -- {primary}",
		"tP": "open --tab -- {primary}",
		"wP": "open --window -- {primary}",

		"r": "reload",
		"R": "reload -f",

		"s": "tab-focus last",
		"S": "cmd-set-text --space --run-on-count :tab-focus",

		"td": "tab-clone",
		"tg": "cmd-set-text --space :tab-give",
		"tt": "open --tab",
		"tu": "undo",

		"u": "scroll-page 0 -0.5",

		"v": "mode-enter caret",
		"V": "mode-enter caret ;; selection-toggle --line",

		"wd": "tab-clone --window",
		"wt": "cmd-set-text --space :tab-take",
		"wu": "undo --window",
		"ww": "open --window",

		"x": "tab-close",
		"X": "close",

		"yd": "yank domain",
		"yD": "yank domain --sel",
		"ym": "yank inline [{title}]({url:yank})",
		"yM": "yank inline [{title}]({url:yank}) --sel",
		"yp": "yank pretty-url",
		"yP": "yank pretty-url --sel",
		"yt": "yank title",
		"yT": "yank title --sel",
		"yy": "yank url",
		"yY": "yank url --sel",

		"z": "fullscreen ;; set statusbar.show always ;; set tabs.show multiple",
		"Z": "fullscreen --enter ;; set statusbar.show in-mode ;; set tabs.show switching",

		"'": None,

		";I": None,
		";O": None,
		";R": None,
		";b": None,
		";f": None,
		";r": None,
		";t": None,

		"<F11>": None,

		"<Alt-1>": None,
		"<Alt-2>": None,
		"<Alt-3>": None,
		"<Alt-4>": None,
		"<Alt-5>": None,
		"<Alt-6>": None,
		"<Alt-7>": None,
		"<Alt-8>": None,
		"<Alt-9>": None,
		"<Alt-m>": None,

		"<Ctrl-Alt-p>": None,
		"<Ctrl-PgDown>": None,
		"<Ctrl-PgUp>": None,
		"<Ctrl-Return>": None,
		"<Ctrl-Shift-Tab>": None,
		"<Ctrl-Shift-n>": None,
		"<Ctrl-Shift-t>": None,
		"<Ctrl-Tab>": None,

		"<Ctrl-^>": None,
		"<Ctrl-a>": None,
		"<Ctrl-b>": None,
		"<Ctrl-p>": None,
		"<Ctrl-x>": None,

		"@": None,
		"[[": None,
		"]]": None,
		"`": None,
		"ad": None,
		"B": None,
		"cd": None,
		"co": None,
		"D": None,
		"gB": None,
		"gb": None,

		"g$": None,
		"g0": None,
		"g^": None,
		"ga": None,
		"gC": None,
		"gD": None,
		"gf": None,
		"gJ": None,
		"gK": None,
		"gm": None,
		"go": None,
		"gO": None,
		"gd": None,

		"J": None,
		"K": None,
		"M": None,
		"O": None,
		"PP": None,
		"Pp": None,
		"pP": None,
		"pp": None,
		"q": None,
		"Sb": None,
		"sf": None,
		"Sh": None,
		"sk": None,
		"sl": None,
		"Sq": None,
		"Ss": None,
		"ss": None,
		"T": None,
		"tCH": None,
		"tCh": None,
		"tcH": None,
		"tch": None,
		"tCu": None,
		"tcu": None,
		"tIH": None,
		"tIh": None,
		"tiH": None,
		"tih": None,
		"tIu": None,
		"tiu": None,
		"tPH": None,
		"tPh": None,
		"tpH": None,
		"tph": None,
		"tPu": None,
		"tpu": None,
		"tSH": None,
		"tSh": None,
		"tsH": None,
		"tsh": None,
		"tSu": None,
		"tsu": None,
		"U": None,
		"wB": None,
		"wi": None,
		"wIf": None,
		"wIh": None,
		"wIj": None,
		"wIk": None,
		"wIl": None,
		"wIw": None,
		"wO": None,
		"xO": None,
		"xo": None,
		"ZQ": None,
		"ZZ": None,
		"{{": None,
		"}}": None,
	},
	"prompt": {
		"<Alt-u>": "spawn --userscript qute-bitwarden --username-only",
		"<Alt-p>": "spawn --userscript qute-bitwarden --password-only",
	},
}
