import re

# https://codebeautify.org/python-formatter-beautifier

# TODO 
# - g
# - private
# - queue tab opens

c.bindings.commands = {
    "normal": {
        "'": None,
        ";I": None,
        ";O": None,
        ";R": None,
        ";Y": "hint links yank-primary",
        ";b": None,
        ";d": "hint links download",
        ";f": None,
        ";h": "hint all hover",
        ";i": "hint images",
        ";o": "hint links fill :open {hint-url}",
        ";r": None,
        ";t": None,
        ";y": "hint links yank",
        "<Alt-1>": None,
        "<Alt-2>": None,
        "<Alt-3>": None,
        "<Alt-4>": None,
        "<Alt-5>": None,
        "<Alt-6>": None,
        "<Alt-7>": None,
        "<Alt-8>": None,
        "<Alt-9>": None,
        "<Alt-m>": None,
        "<Ctrl-a>": None,
        "<Ctrl-Alt-p>": None,
        "<Ctrl-b>": None,
        "<Ctrl-d>": "scroll-page 0 0.5",
        "<Ctrl-f>": "cmd-set-text /",
        "<Ctrl-PgDown>": None,
        "<Ctrl-PgUp>": None,
        "<Ctrl-Return>": None,
        "<Ctrl-Shift-n>": None,
        "<Ctrl-Shift-t>": None,
        "<Ctrl-Shift-Tab>": None,
        "<Ctrl-t>": "open --tab",
        "<Ctrl-Tab>": None,
        "<Ctrl-u>": "scroll-page 0 -0.5",
        "<Ctrl-x>": None,
        "<Ctrl-^>": None,
        "<Ctrl-h>": "tab-move -",
        "<Ctrl-p>": None,
        "<Escape>": "clear-messages ;; clear-keychain ;; search",
        "<F11>": None,
        "@": None,
        "B": None,
        "D": None,
        "F": "hint links tab-bg",
        "G": "scroll-to-perc",
        "H": "back",
        "J": None,
        "K": None,
        "L": "forward",
        "M": None,
        "N": "search-prev",
        "O": None,
        "PP": None,
        "Pp": None,
        "R": "reload -f",
        "Sb": None,
        "Sh": None,
        "Sq": None,
        "Ss": None,
        "T": None,
        "U": None,
        "V": "mode-enter caret ;; selection-toggle --line",
        "ZQ": None,
        "ZZ": None,
        "[[": None,
        "]]": None,
        "`": None,
        "ad": None,
        "b": "cmd-set-text --space :quickmark-load",
        "cd": None,
        "co": None,
        "d": "scroll-page 0 0.5",
        "f": "hint links",
        "gB": None,
        "gb": None,
        "h": "tab-prev",
        "i": "mode-enter insert",
        "j": "scroll down",
        "k": "scroll up",
        "l": "tab-next",
        "m": "cmd-set-text --space :bookmark-load",
        "n": "search-next",
        "o": "cmd-set-text --space :open",
        "pP": None,
        "pp": None,
        "q": None,
        "r": "reload",
        "sf": None,
        "sk": None,
        "sl": None,
        "ss": None,
        "tCH": None,
        "tCh": None,
        "tCu": None,
        "tIH": None,
        "tIh": None,
        "tIu": None,
        "tPH": None,
        "tPh": None,
        "tPu": None,
        "tSH": None,
        "tSh": None,
        "tSu": None,
        "tcH": None,
        "tch": None,
        "tcu": None,
        "th": "back --tab",
        "tiH": None,
        "tih": None,
        "tiu": None,
        "tl": "forward --tab",
        "tpH": None,
        "tph": None,
        "tpu": None,
        "tsH": None,
        "tsh": None,
        "tsu": None,
        "u": "scroll-page 0 -0.5",
        "v": "mode-enter caret",
        "wB": None,
        "wIf": None,
        "wIh": None,
        "wIj": None,
        "wIk": None,
        "wIl": None,
        "wIw": None,
        "wO": None,
        "wP": "open --window -- {primary}",
        "wb": "cmd-set-text --space :quickmark-load --window",
        "wf": "hint links window",
        "wh": "back --tab",
        "wi": None,
        "wl": "forward --window",
        "wo": "cmd-set-text --space :open --window",
        "wp": "open --window -- {clipboard}",
        "xO": None,
        "xo": None,
        "yD": "yank domain --sel",
        "yM": "yank inline [{title}]({url:yank}) --sel",
        "yP": "yank pretty-url --sel",
        "yT": "yank title --sel",
        "yY": "yank url --sel",
        "yd": "yank domain",
        "ym": "yank inline [{title}]({url:yank})",
        "yp": "yank pretty-url",
        "yt": "yank title",
        "yy": "yank url",
        "{{": None,
        "}}": None,
        "tb": "cmd-set-text --space :quickmark-load --tab",
        "tm": "cmd-set-text --space :bookmark-load --tab",
        "wm": "cmd-set-text --space :bookmark-load --window",
        "tu": "undo",
        "wu": "undo --window",
        "td": "tab-clone",
        "wd": "tab-clone --window",
        "tg": "cmd-set-text --space :tab-give",
        "wt": "cmd-set-text --space :tab-take",
        "p": "open -- {clipboard}",
        "tp": "open --tab -- {clipboard}",
        "P": "open -- {primary}",
        "tP": "open --tab -- {primary}",
        "to": "cmd-set-text --space :open --tab",
        "e": "cmd-set-text :open {url:pretty}",
        "te": "cmd-set-text :open --tab {url:pretty}",
        "we": "cmd-set-text :open --window {url:pretty}",
        "E": "edit-url",
        "tE": "edit-url --tab",
        "wE": "edit-url --window",
        "tt": "open --tab",
        "ww": "open --window",
        "x": "tab-close",
        "X": "close",
        "s": "tab-focus last",
        "S": "cmd-set-text --space --run-on-count :tab-focus",
        "tf": "hint links tab",
        "a": "hint all",
        "A": "hint all tab-bg",
        "ta": "hint all tab",
        "wa": "hint all window",
        ";to": "hint links fill :open --tab {hint-url}",
        ";wo": "hint links fill :open --window {hint-url}",
        "Z": "fullscreen --enter ;; set statusbar.show in-mode ;; set tabs.show switching",
        "z": "fullscreen ;; set statusbar.show always ;; set tabs.show multiple",
        "<Ctrl-Shift-b>": "bookmark-list --tab",
        "<Ctrl-Shift-h>": "history --tab",
        "ct": "tab-only",
        "cw": "window-only",
        "cl": "tab-only --prev",
        "ch": "tab-only --next",
        "<Ctrl-l>": "tab-move +",
        "<Alt-b>": "spawn --userscript --verbose qute-bitwarden.py",
        "<Alt-u>": "spawn --userscript --verbose qute-bitwarden.py --username-only",
        "<Alt-p>": "spawn --userscript --verbose qute-bitwarden.py --password-only",
        "<Alt-d>": "set colors.webpage.darkmode.enabled true",
        "<Alt-l>": "set colors.webpage.darkmode.enabled false",
    },
    "prompt": {
        "<Alt-u>": "spawn --userscript qute-bitwarden --username-only",
        "<Alt-p>": "spawn --userscript qute-bitwarden --password-only",
    },
}

# always print defaults and user
binds_all = {}

# user bindings always come back as "<Ctrl+Shift+f" , defaults as "<Ctrl-Shift-F"
def normalise(key):
    if re.match('.*(shift|ctrl|alt)[+-].*', key, flags=re.IGNORECASE):
        key = key.lower()
        key = re.sub('ctrl[+-]', 'Ctrl-', key)
        key = re.sub('alt[+-]', 'Alt-', key)
        key = re.sub('shift[+-]', 'Shift-', key)
    return key

# collect default bindings
for mode, binds in c.bindings.default.items():
    for key, cmd in binds.items():
        key = normalise(key)
        binds_all[f'{mode}{key}'] = f'{mode:12}D  {key:18}{cmd}'

# collect user bindings, removing any unbindings
for mode, binds in c.bindings.commands.items():
    for key, cmd in binds.items():
        if cmd is None:
            binds[key] = None
        else:
            key = normalise(key)
            binds_all[f'{mode}{key}'] = f'{mode:12}   {key:18}{cmd}'

# sort by mode/key and print
for mode_key in sorted(binds_all, key=str.lower):
    print(f'{binds_all[mode_key]}')

