#!/usr/bin/env bash

# https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory
# https://github.com/pyvelepor/todo_distributed/blob/62e1e66181f4216cfc1fb2a16d080dbfb57dd403/sync

action=$1

function usage {
	echo "  $(basename $0)"
        echo "  Uses the commit, pull and push addons to keep the local "
        echo "  repository at $TODO_DIR and remote repository in sync. "
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

$TODO_FULL_SH commit
$TODO_FULL_SH pull
$TODO_FULL_SH push
