#!/bin/zsh

# always server side decorations
riverctl rule-add ssd

# floating
riverctl rule-add -title "Open File" float
riverctl rule-add -title "Open Folder" float
riverctl rule-add -title "*references*" float
riverctl rule-add -title "*wants to open*" float
riverctl rule-add -title "*wants to save*" float
riverctl rule-add -title "All Files" float
riverctl rule-add -title "3D Print — OpenSCAD" float
riverctl rule-add -app-id nm-openconnect-auth-dialog float
riverctl rule-add -app-id "blueman-*" float

# full
riverctl rule-add -app-id gamescope fullscreen

# tiled
riverctl rule-add -title "*OpenSCAD" no-float

# behaviour
riverctl attach-mode bottom
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
