#!/bin/zsh

# keyboard
riverctl set-repeat 50 400

# mouse
riverctl input "*Mouse" pointer-accel 0
riverctl input "*Mouse" accel-profile none

# pads
riverctl input "*Trackpad" tap enabled
riverctl input "*Trackpad" natural-scroll enabled

riverctl input "*Touchpad" tap enabled
riverctl input "*Touchpad" natural-scroll enabled

# this is slow hence background it
if [ "$(whence libinput-gestures-setup)" ]; then
	libinput-gestures-setup restart &
fi
