#!/bin/zsh

# keyboard
riverctl set-repeat 50 400

# mouses
riverctl input "*" pointer-accel 0
riverctl input "*" accel-profile none

# pads
riverctl input "*" tap enabled
riverctl input "*" natural-scroll enabled

# this is slow hence background it
if [ "$(whence libinput-gestures-setup)" ]; then
	libinput-gestures-setup restart &
fi
