#!/bin/zsh

mod1="Super"
mod2="$mod1+Shift"
mod3="$mod2+Control"
mod4="$mod3+Alt"

#
# mouse
#
riverctl map-pointer normal $mod1 BTN_LEFT move-view
riverctl map-pointer normal $mod1 BTN_RIGHT resize-view
riverctl map-pointer normal $mod1 BTN_MIDDLE toggle-float
riverctl map-pointer normal $mod2 BTN_MIDDLE toggle-fullscreen

#
# thumbs
#

# $mod1 BackSpace hardcoded to c-w by keyd
riverctl map normal $mod2 BackSpace close
riverctl map normal $mod3 BackSpace spawn "steam -shutdown"
riverctl map normal $mod4 backspace exit

riverctl map normal $mod1 Escape spawn term
# mod2 is alacritty term

riverctl map normal $mod1 Tab spawn b
riverctl map normal $mod2 Tab spawn bp

riverctl map normal $mod1 Delete spawn "exec \$(menjar -d ${XDG_DATA_HOME}/applications -d ${XDG_DATA_HOME}/flatpak/exports/share/applications) > /dev/null 2>&1"
riverctl map normal $mod2 Delete spawn "bemenu-run > /dev/null 2>&1"

riverctl map normal $mod1 Return focus-view next
riverctl map normal $mod2 Return focus-view previous

riverctl map normal $mod1 Space send-layout-cmd wideriver "--layout-toggle"
riverctl map normal $mod2 Space focus-previous-tags

#
# left
#

# $@
tag=1
for k in "a" "o" "e" "u" "i" "semicolon" "comma" "period" "p" "y"; do

	riverctl map normal $mod1 $k set-focused-tags $tag
	riverctl map normal $mod2 $k spawn "riverctl set-view-tags ${tag} ; riverctl set-focused-tags ${tag}"
	riverctl map normal $mod3 $k set-view-tags $tag
	tag=$(($tag << 1))
done

# 'qx
riverctl map normal $mod1 j focus-view next
riverctl map normal $mod2 j swap next

riverctl map normal $mod1 k focus-view previous
riverctl map normal $mod2 k swap previous

#
riverctl map normal $mod1 Left focus-output previous
riverctl map normal $mod2 Left spawn "riverctl send-to-output -current-tags previous && riverctl focus-output previous"
riverctl map normal $mod3 Left send-to-output previous

riverctl map normal $mod1 Right focus-output next
riverctl map normal $mod2 Right spawn "riverctl send-to-output -current-tags next && riverctl focus-output next"
riverctl map normal $mod3 Right send-to-output next

#
# right
#

# /
riverctl map normal $mod1 f toggle-fullscreen
riverctl map normal $mod3 f spawn "volraisemic"

riverctl map normal $mod1 g send-layout-cmd wideriver "--count +1"
riverctl map normal $mod3 g spawn "volraise"

riverctl map normal $mod1 c send-layout-cmd wideriver "--count 1"

riverctl map normal $mod1 r send-layout-cmd wideriver "--count -1"

riverctl map normal $mod1 l send-layout-cmd wideriver "--stack dwindle"
riverctl map normal $mod2 l send-layout-cmd wideriver "--stack even"
riverctl map normal $mod3 l send-layout-cmd wideriver "--stack diminish"

#
riverctl map normal $mod1 d toggle-float
riverctl map normal $mod3 d spawn "vollowermic"

riverctl map normal $mod1 h swap previous
riverctl map normal $mod2 h spawn "riverctl send-layout-cmd wideriver '--count +1' && riverctl focus-view next"
riverctl map normal $mod3 h spawn "vollower"

riverctl map normal $mod1 t spawn "riverctl send-layout-cmd wideriver '--layout monocle' && riverctl send-layout-cmd wideriver '--layout left'"
riverctl map normal $mod2 t spawn "riverctl send-layout-cmd wideriver '--layout monocle' && riverctl send-layout-cmd wideriver '--layout wide'"

riverctl map normal $mod1 n swap next
riverctl map normal $mod2 n spawn "riverctl send-layout-cmd wideriver '--count -1' && riverctl focus-view previous"

riverctl map normal $mod1 s spawn "sss"
riverctl map normal $mod2 s spawn "wl-color-picker > /dev/null 2>&1"

riverctl map normal $mod1 Minus spawn "ssa"

# b
riverctl map normal $mod3 b spawn "volmutemic"

riverctl map normal $mod1 m send-layout-cmd wideriver "--ratio -0.025"
riverctl map normal $mod3 m spawn "volmute"

riverctl map normal $mod1 w send-layout-cmd wideriver "--ratio 0.5"
riverctl map normal $mod2 w send-layout-cmd wideriver "--ratio 0.35"

riverctl map normal $mod1 v send-layout-cmd wideriver "--ratio +0.025"

riverctl map normal $mod1 z spawn "way-displays --toggle SCALING"

#
# special
#
riverctl map normal None XF86AudioMute         spawn "volmute"
riverctl map normal None XF86AudioMicMute      spawn "volmutemic"
riverctl map normal None XF86AudioRaiseVolume  spawn "volraise"
riverctl map normal None XF86AudioLowerVolume  spawn "vollower"
riverctl map normal None XF86MonBrightnessUp   spawn "sudo brightnessctl s 10%+"
riverctl map normal None XF86MonBrightnessDown spawn "sudo brightnessctl s 10%-"

#
# meta
#
riverctl map normal None XF86Paste spawn primary-paste
