[window]
decorations = "Transparent"
padding = { x = 0, y = 18 }
dynamic_padding = true

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"
args = [ "-l" ]

[font]
offset = { y = 1 }

[keyboard]
bindings = [

# { key = "Escape", mods = "Command|Option|Shift|Control", action = "CreateNewWindow"                                     },
{ key = "Escape", mods = "Command",                      action = "CreateNewWindow"                                     },

{ key = "Return", mods = "Command",                      action = "ToggleViMode",   mode = "~AppCursor|~AppKeypad|~Alt" },

{ key = "L", mods = "Command",                           chars = "\u000c",          mode = "~AppCursor|~AppKeypad|~Alt" },
{ key = "L", mods = "Command",                           action = "ClearHistory",   mode = "~AppCursor|~AppKeypad|~Alt" },

]
