#!/bin/sh
# Assign ownership of the console to the invoking user
#
# By convention, both xconsole and xterm -C check that the
# console is owned by the invoking user and is readable before attaching
# the console output.  This way a random user can invoke xterm -C without
# causing serious grief.
#

# kill off any xmessages from systemd-boot-xmessage first
pkill xmessage

chown $USER /dev/console
exec /usr/bin/sessreg  -a -w "/var/log/wtmp" -u "/run/utmp" \
        -x "/etc/X11/xdm/Xservers" -l $DISPLAY -h "" $USER
