#!/bin/sh

# start the display mirrored
# also "reboot" displays for monitors that don't like to boot cold... looking at you ASUS ROG monitors
xLayoutDisplay -m

# show some useful buttons in the top left
systemd-boot-xmessage -geometry +0+0 &

xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
