#!/bin/sh

# start the display mirrored
# also "reboot" displays for monitors that don't like to boot cold... looking at you ASUS ROG monitors
xLayoutDisplay -m

# background to match desktop
xsetroot -solid gray20

# boot buttons
systemd-boot-xmessage &

xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
