[window]
decorations = "Full"
padding = { x = 0, y = 0 }
dynamic_padding = true

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"
args = [ "-l" ]

[font]
offset = { y = 1 }

[keyboard]
bindings = [

# mapped by karabiner querty l
# not sure why C|C|O|S does not work directly
{ key = "N",      mods = "Command|Control|Shift",             action = "CreateNewWindow"                                     },

{ key = "Return", mods = "Command",                           action = "ToggleViMode",   mode = "~AppCursor|~AppKeypad|~Alt" },

{ key = "L",      mods = "Command",                           chars = "\u000c",          mode = "~AppCursor|~AppKeypad|~Alt" },
{ key = "L",      mods = "Command",                           action = "ClearHistory",   mode = "~AppCursor|~AppKeypad|~Alt" },

{ key = "W",      mods = "Command",                           chars = "" },
{ key = "W",      mods = "Command|Shift",                     action = "Quit" },

]
