#!/bin/zsh

# used by xdg-desktop-portal-wlr
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

echo "llllllllll1" > /tmp/rlw.state

way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &
mako > /tmp/mako.${XDG_VTNR}.${USER}.log 2>&1 &

swayidle -w \
	timeout 900 'swaylock -f -c ${BASE01}' \
	before-sleep 'swaylock -f -c ${BASE01}' \
	> /tmp/swayidle.${XDG_VTNR}.${USER}.log 2>&1 &

mod1="Super"
mod2="$mod1+Control"
mod3="$mod2+Shift"

# mouse
riverctl map-pointer normal $mod1 BTN_LEFT move-view
riverctl map-pointer normal $mod1 BTN_RIGHT resize-view
riverctl map-pointer normal $mod1 BTN_MIDDLE toggle-float
riverctl map-pointer normal $mod2 BTN_MIDDLE toggle-fullscreen

# thumbs
riverctl map normal $mod1 BackSpace focus-output next
riverctl map normal $mod2 BackSpace spawn "riverctl send-to-output next && riverctl focus-output next"
riverctl map normal $mod3 BackSpace send-to-output next
riverctl map normal $mod1 Escape swap next
riverctl map normal $mod2 Escape swap previous
riverctl map normal $mod1 Tab spawn "bemenu-run > /dev/null 2>&1"
riverctl map normal $mod2 Tab spawn "exec \$(menjar -d ${XDG_DATA_HOME}/applications) > /dev/null 2>&1"
riverctl map normal $mod1 Delete spawn "term > /dev/null 2>&1 &!"
riverctl map normal $mod2 Delete spawn "browser > /dev/null 2>&1 &!"
riverctl map normal $mod3 Delete spawn "way-displays -s AUTO_SCALE off ; way-displays -d SCALE M28U ; steam > /dev/null 2>&1"
riverctl map normal $mod1 Return focus-view next
riverctl map normal $mod2 Return focus-view previous
riverctl map normal $mod1 Space spawn 'rivercarro-wrapper layout toggle'
riverctl map normal $mod2 Space toggle-fullscreen
riverctl map normal $mod3 Space toggle-float

# left
tag=1
for k in "a" "o" "e" "u" "i" "semicolon" "comma" "period" "p" "y"; do

	riverctl map normal $mod1 $k spawn "rivercarro-wrapper tag-focus $tag"
	riverctl map normal $mod2 $k spawn "rivercarro-wrapper tag-move $tag"
	riverctl map normal $mod3 $k set-view-tags $tag
	tag=$(($tag << 1))
done

riverctl map normal $mod1 q close

if [ "${HOST}" = "gigantor" ]; then
	# if exiting wayland cleanly: gigantor will sleep when lid closed
	riverctl map normal $mod3 q spawn "pkill -9 river"
else
	riverctl map normal $mod3 q exit
fi

riverctl map normal $mod1 equal send-layout-cmd rivercarro "main-ratio 0.5"

#right
riverctl map normal $mod1 plus send-layout-cmd rivercarro "main-ratio +0.025"

riverctl map normal $mod1 minus send-layout-cmd rivercarro "main-ratio -0.025"

riverctl map normal $mod3 f spawn "volraisemic"

riverctl map normal $mod3 g spawn "volraise"

riverctl map normal $mod3 l spawn "swaylock -f -c \${BASE01} > /dev/null 2>&1"

riverctl map normal $mod3 d spawn "vollowermic"

riverctl map normal $mod3 h spawn "vollower"

riverctl map normal $mod3 t spawn "bell"

riverctl map normal $mod3 n spawn "ssa"

riverctl map normal $mod3 s spawn "sss"

riverctl map normal $mod3 minus spawn "sudo systemctl suspend"

riverctl map normal $mod3 b spawn "volmutemic"

riverctl map normal $mod3 m spawn "volmute"

riverctl map normal $mod3 v spawn "way-displays -s AUTO_SCALE on  ; way-displays -s SCALE M28U 1.75"

riverctl map normal $mod3 z spawn "way-displays -s AUTO_SCALE off ; way-displays -d SCALE M28U"

riverctl map normal $mod3 backslash spawn "sudo systemctl hibernate"

# special
riverctl map normal None XF86AudioMute         spawn "volmute"
riverctl map normal None XF86AudioMicMute      spawn "volmutemic"
riverctl map normal None XF86AudioRaiseVolume  spawn "volraise"
riverctl map normal None XF86AudioLowerVolume  spawn "vollower"
riverctl map normal None XF86MonBrightnessUp   spawn "sudo brightnessctl s 10%+"
riverctl map normal None XF86MonBrightnessDown spawn "sudo brightnessctl s 10%-"

# appearance
riverctl background-color "0x${BASE00#*#}"
riverctl border-color-unfocused "0x${BASE01#*#}"
riverctl border-color-focused "0x${BASE04#*#}"
riverctl border-color-urgent "0x${BASE03#*#}"
riverctl border-width 2

# ssd by default
riverctl rule-add ssd

# csd
riverctl rule-add csd -app-id zoom

# floating
riverctl rule-add float title "Open File"
riverctl rule-add float title "Open Folder"
riverctl rule-add float -app-id nm-openconnect-auth-dialog
riverctl rule-add float -app-id zoom

# behaviour
riverctl attach-mode bottom
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change

# input
${XDG_CONFIG_HOME}/river/input
if [ "$(whence libinput-gestures-setup)" ]; then
	libinput-gestures-setup restart > /dev/null 2>&1
fi

# optional bar contents
sed -E "s|// *(.*#${HOST})|\1|g" $XDG_CONFIG_HOME/waybar/config.template > $XDG_CONFIG_HOME/waybar/config

# bar style
sed -e "s/\${FONT_SIZE_PT}/${FONT_SIZE_PT}/g" $XDG_CONFIG_HOME/waybar/style.template.css > $XDG_CONFIG_HOME/waybar/style.css

riverctl spawn waybar

# run
riverctl default-layout rivercarro
exec rivercarro -inner-gaps 0 -outer-gaps 0 \
	-main-location left -main-ratio 0.5

