#!/bin/sh

# start the display mirrored
# also "reboot" displays for monitors that don't like to boot cold... looking at you ASUS ROG monitors
xlayoutlisplay -m

# background to match desktop
xsetroot -solid gray20

# boot buttons
systemd-boot-xmessage &
